language: cpp

compiler:
- clang
- gcc

env:
  matrix:
    - QT_BASE=4
    - QT_BASE=5

before_install:
- if [ "$QT_BASE" = "5" ]; then sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y; fi
- sudo apt-get update -qq

install:
- if [ "$QT_BASE" = "4" ]; then sudo apt-get install -qq qt4-qmake qt4-dev-tools; fi
- if [ "$QT_BASE" = "5" ]; then sudo apt-get install -qq ubuntu-sdk qtquick1-5-dev; fi

before_script:
- if [ "$QT_BASE" = "4" ]; then qmake; fi
- if [ "$QT_BASE" = "5" ]; then /usr/lib/x86_64-linux-gnu/qt5/bin/qmake; fi

script:
- make

branches:
  only:
    - master

#notifications:
  #email:
    #recipients:
    #on_failure: always
    #on_success: change
