language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=4
- QT_BASE=5
- QT_BASE=5 QMAKE_OPTS="CONFIG+=static staticlib"

matrix:
  allow_failures:
  - compiler: clang
    env: QT_BASE=5
  - compiler: clang
    env: QT_BASE=5 QMAKE_OPTS="CONFIG+=static staticlib"

services:
  - mysql
  - postgresql

before_install:
- if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y --keyserver pool.sks-keyservers.net; fi
- sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y --keyserver pool.sks-keyservers.net
- sudo apt-get update -qq

install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi
- if [ "$QT_BASE" = "4" ]; then sudo apt-get install -qq qt4-default qt4-qmake qt4-dev-tools libqt4-sql-mysql libqt4-sql-psql libqt4-sql-sqlite; fi
- if [ "$QT_BASE" = "5" ]; then sudo apt-get install -qq qt5-default qt5-qmake qtbase5-dev-tools libqt5sql5-mysql libqt5sql5-psql libqt5sql5-sqlite; fi

before_script:
- mv tests/mysql/MysqlConfig.h.travis tests/mysql/MysqlConfig.h
- mv tests/postgresql/PostgresqlConfig.h.travis tests/postgresql/PostgresqlConfig.h

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "CONFIG+=NoFirebird"
- make check

branches:
  only:
  - develop
  - master
