version: 1.5.1_{build}

os: unstable

services:
- mysql
- postgresql

environment:
  matrix:
  - BUILD: Qt5.3.2-mingw32
    QTDIR: C:\Qt\Qt5.3.2\5.3\mingw482_32
    COMPILERDIR: C:\Qt\Qt5.3.2\Tools\mingw482_32\bin
    MAKE: mingw32-make
    CHECK: mingw32-make check
  - BUILD: Qt5.3.2-x86-msvc2013
    COMPILERBAT: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\vcvars32.bat
    MAKE: nmake
    CHECK: nmake check
    QTSUB: 5.3\msvc2013_opengl
    QTDOWNLOAD1: http://download.qt-project.org/online/qtsdkrepository/windows_x86/desktop/qt5_53/qt.53.win32_msvc2013_opengl/5.3.2-0qt5_essentials.7z
    QTARCHIVE1: 5.3.2-0qt5_essentials.7z
    QTDOWNLOAD2: http://download.qt-project.org/online/qtsdkrepository/windows_x86/desktop/qt5_53/qt.53.win32_msvc2013_opengl/5.3.2-0icu_52_1_msvc_2013_32.7z
    QTARCHVIE2: 5.3.2-0icu_52_1_msvc_2013_32.7z

install:
# fix git\bin bug
- set "PATH=%PATH:Git\bin;=Git\cmd;%"
# prepare extern install
- choco install curl 7zip
- mkdir extern
- cd extern
# install Qt
- mkdir Qt
- cd Qt
- if defined QTSUB set QTDIR=%CD%\%QTSUB%
- if defined QTDOWNLOAD1 curl -kLO %QTDOWNLOAD1%
- if defined QTARCHIVE1 7z x %QTARCHIVE1% >nul
- if defined QTDOWNLOAD2 curl -kLO %QTDOWNLOAD2%
- if defined QTARCHIVE2 7z x %QTARCHIVE2% >nul
- cd ..
# install mysql driver
- curl -kLO https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.5-win32.zip
- 7z x mysql-connector-c-6.1.5-win32.zip >nul
- set PATH=%PATH%;%CD%\mysql-connector-c-6.1.5-win32\lib
# install postgres driver
- curl -kLO http://get.enterprisedb.com/postgresql/postgresql-9.3.5-1-windows-binaries.zip
- 7z x postgresql-9.3.5-1-windows-binaries.zip >nul
# finish install
- cd ..
- mkdir build

before_build:
- set "PATH=%QTDIR%\bin;%PATH%"
- if defined COMPILERDIR set "PATH=%COMPILERDIR%;%PATH%"
- if defined COMPILERBAT %COMPILERBAT%
- move tests\mysql\MysqlConfig.h.appveyor tests\mysql\MysqlConfig.h
- move tests\postgresql\PostgresqlConfig.h.appveyor tests\postgresql\PostgresqlConfig.h

build_script:
- mkdir build\%BUILD%
- cd build\%BUILD%
- qmake -r "CONFIG+=NO_QSM_FIREBIRD"
- "%MAKE%"
- cd ..\..

test_script:
- set PATH=%CD%\extern\pgsql\bin;%PATH%
- cd build\%BUILD%
- "%CHECK%"
- cd ..\..

branches:
  only:
  - appveyor
