version: 1.5.1_{build}

os: unstable

services:
- mysql
- postgresql

install:
- set "QTBASE=C:\Qt\Qt5.3.2"
- set "QTDIR=%QTBASE%\5.3\mingw482_32"
- set "QTSRC=%QTBASE%\5.3\Src\qtbase"
- set "MINGWDIR=%QTBASE%\Tools\mingw482_32"
- set "PATH=%QTDIR%\bin;%MINGWDIR%\bin;%PATH%"
- set "PATH=%PATH:Git\bin;=Git\cmd;%"
- mkdir extern
- cd extern
- choco install curl 7zip
# install mysql driver
- curl -kLO https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.5-win32.zip
- 7z x mysql-connector-c-6.1.5-win32.zip
- set PATH=%PATH%;%CD%\mysql-connector-c-6.1.5-win32\lib
# install postgres driver
- curl -kLO http://get.enterprisedb.com/postgresql/postgresql-9.3.5-1-windows-binaries.zip
- 7z x postgresql-9.3.5-1-windows-binaries.zip
- set PATH=%PATH%;%CD%\pgsql\lib
- cd ..

before_build:
- move tests\mysql\MysqlConfig.h.appveyor tests\mysql\MysqlConfig.h
- move tests\postgresql\PostgresqlConfig.h.appveyor tests\postgresql\PostgresqlConfig.h

build_script:
- dir extern
- qmake -r "CONFIG+=NO_QSM_FIREBIRD"
- mingw32-make

test_script:
- mingw32-make check

branches:
  only:
  - appveyor
