version: 1.5.1_{build}

os: unstable

services:
- mysql
- postgresql

environment:
  matrix:
  - BUILD: Qt5.3.2-mingw
    QTDIR: C:\Qt\Qt5.3.2\5.3\mingw482_32
    COMPILERDIR: C:\Qt\Qt5.3.2\Tools\mingw482_32\bin
    MAKE: mingw32-make
    CHECK: mingw32-make check
  #- BUILD: Qt5.3.2-msvc2013
  # TODO: no other Qt installation currently available
  # NOTE: Silent installers of choco miss mysql & postgresql plugins
  # NOTE: Official installers are not silent

install:
# fix git\bin bug
- set "PATH=%PATH:Git\bin;=Git\cmd;%"
# prepare extern install
- choco install curl 7zip
- mkdir extern
- cd extern
# install mysql driver
- curl -kLO https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.5-win32.zip
- 7z x mysql-connector-c-6.1.5-win32.zip >nul
- set PATH=%PATH%;%CD%\mysql-connector-c-6.1.5-win32\lib
# install postgres driver
- curl -kLO http://get.enterprisedb.com/postgresql/postgresql-9.3.5-1-windows-binaries.zip
- 7z x postgresql-9.3.5-1-windows-binaries.zip >nul
# finish install
- cd ..

before_build:
- set "PATH=%QTDIR%\bin;%COMPILERDIR%;%PATH%"
- move tests\mysql\MysqlConfig.h.appveyor tests\mysql\MysqlConfig.h
- move tests\postgresql\PostgresqlConfig.h.appveyor tests\postgresql\PostgresqlConfig.h

build_script:
- qmake -r "CONFIG+=NO_QSM_FIREBIRD"
- %MAKE%

test_script:
- set PATH=%CD%\extern\pgsql\bin;%PATH%
- %CHECK%

branches:
  only:
  - appveyor
