version: 1.5.1_{build}

os: unstable

services:
- mysql
- postgresql

environment:
  PRO_FILE: 'C:\projects\qsqlmigrator\QSqlMigrator.pro'

  matrix:
  - BUILD: 'Qt5.3.2-x86-msvc2013'
    COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86'
    MAKE: nmake
    CHECK: nmake check
    QMAKESPEC: win32-msvc2013
    QTSUB: '5.3\msvc2013_opengl'
    QTDOWNLOAD1: http://download.qt-project.org/online/qtsdkrepository/windows_x86/desktop/qt5_53/qt.53.win32_msvc2013_opengl/5.3.2-0qt5_essentials.7z
    QTARCHIVE1: '5.3.2-0qt5_essentials.7z'
    QTDOWNLOAD2: http://download.qt-project.org/online/qtsdkrepository/windows_x86/desktop/qt5_53/qt.53.win32_msvc2013_opengl/5.3.2-0icu_52_1_msvc_2013_32.7z
    QTARCHIVE2: '5.3.2-0icu_52_1_msvc_2013_32.7z'

  - BUILD: 'Qt5.3.2-x64-msvc2013'
    COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64'
    MAKE: nmake
    CHECK: nmake check
    QMAKESPEC: win32-msvc2013
    QTSUB: '5.3\msvc2013_64_opengl'
    QTDOWNLOAD1: http://download.qt-project.org/online/qtsdkrepository/windows_x86/desktop/qt5_53/qt.53.win64_msvc2013_64_opengl/5.3.2-0qt5_essentials.7z
    QTARCHIVE1: '5.3.2-0qt5_essentials.7z'
    QTDOWNLOAD2: http://download.qt-project.org/online/qtsdkrepository/windows_x86/desktop/qt5_53/qt.53.win64_msvc2013_64_opengl/5.3.2-0icu_52_1_msvc_2013_64.7z
    QTARCHIVE2: '5.3.2-0icu_52_1_msvc_2013_64.7z'

  - BUILD: Qt4.8.6-x86-msvc2010
    QMAKE_OPTIONS: "CONFIG+=NO_QSM_POSTGRES"
    COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86'
    MAKE: nmake release
    CHECK: 'cd ..\..\bin && tst_SqliteTest.exe'
    QMAKESPEC: win32-msvc2010
    QTMOVE: '$OUTDIR\bin 4.8.6-msvc2010'
    QTSUB: '4.8.6-msvc2010'
    QTDOWNLOAD1: http://download.qt-project.org/official_releases/qt/4.8/4.8.6/qt-opensource-windows-x86-vs2010-4.8.6.exe
    QTARCHIVE1: 'qt-opensource-windows-x86-vs2010-4.8.6.exe'
    QTARCHIVE1_OPTS: '"-ir!?OUTDIR\*" "-xr!*doc\*" "-xr!*examples\*" "-xr!*demos\*"'

  #- BUILD: Qt5.3.2-mingw32
  #QTDIR: 'C:\Qt\Qt5.3.2\5.3\mingw482_32'
  #COMPILERDIR: 'C:\Qt\Qt5.3.2\Tools\mingw482_32\bin'
  #QMAKESPEC: win32-g++
  #MAKE: mingw32-make
  #CHECK: mingw32-make check

install:
# fix git\bin bug for mingw build
- set "PATH=%PATH:Git\bin;=Git\cmd;%"

# prepare extern install
- choco install curl 7zip dependencywalker
- mkdir extern
- cd extern

# install Qt
- mkdir Qt
- cd Qt
- if defined QTDOWNLOAD1 curl -kLO %QTDOWNLOAD1%
- if defined QTARCHIVE1 7z x %QTARCHIVE1_OPTS% %QTARCHIVE1% >nul
- if defined QTDOWNLOAD2 curl -kLO %QTDOWNLOAD2%
- if defined QTARCHIVE2 7z x %QTARCHIVE2_OPTS% %QTARCHIVE2% >nul
- if defined QTMOVE move %QTMOVE%
- if defined QTSUB set "QTDIR=%CD%\%QTSUB%"
- if defined QTDOWNLOAD1 (echo [Paths]&& echo Prefix=..) >%QTDIR%\bin\qt.conf
- cd ..

# install mysql driver
- curl -kLO https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.5-win32.zip
- 7z x mysql-connector-c-6.1.5-win32.zip >nul
- set "PATH=%PATH%;%CD%\mysql-connector-c-6.1.5-win32\lib"

# install postgres driver
- curl -kLO http://get.enterprisedb.com/postgresql/postgresql-9.3.5-1-windows-binaries.zip
- 7z x postgresql-9.3.5-1-windows-binaries.zip >nul

# finish install
- cd ..
- set "PATH=%QTDIR%\bin;%PATH%"
- if defined COMPILERDIR set "PATH=%COMPILERDIR%;%PATH%"
- '%COMPILERBAT%'

before_build:
- move tests\mysql\MysqlConfig.h.appveyor tests\mysql\MysqlConfig.h
- move tests\postgresql\PostgresqlConfig.h.appveyor tests\postgresql\PostgresqlConfig.h

build_script:
- set
- echo "building %BUILD%"
- mkdir build
- mkdir "build\%BUILD%"
- cd "build\%BUILD%"
- qmake -r "CONFIG+=NO_QSM_FIREBIRD" %QMAKE_OPTIONS% %PRO_FILE%
- '%MAKE%'
- cd ..\..

test_script:
- set "PATH=%CD%\extern\pgsql\bin;%PATH%"
#- echo %CD%
#- set
- dir %QTDIR%\bin
#- depends.exe /ot:text.txt /c bin\tst_SqliteTest.exe
#- type text.txt
- cd "build\%BUILD%"
- '%CHECK%'
- cd ..\..

branches:
  only:
  - appveyor
